---
name: Sosicon CI

on:
  push:
    branches-ignore:
      - master
    paths:
      - '**'
      - '.github/workflows/sosicon-ci.yaml'

jobs:

  pre_job:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(BRANCH=${GITHUB_REF#refs/heads/}; echo ${BRANCH//\//-})"

  main:
    runs-on: ubuntu-latest
    needs: pre_job
    env:
      DOCKER_BUILDKIT: 1
      FQ_IMAGE: ${{ format('ghcr.io/arkivverket/sosicon:{0}-{1}', needs.pre_job.outputs.branch, github.sha) }}
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.FQ_IMAGE }}
      - name: Container scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.FQ_IMAGE }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
